### Working with Arrays and Arrays builtin Functions


In [1]:
# Convention for importing numpy
import numpy as np

arr = [6,7,8,9]

# this display the type of datastruture used
print(type(arr))

<class 'list'>


In [4]:
# converting the list to a numpy array type
# uising the np.array(list_object)
a = np.array(arr)
print('The datastruture is now ',type(a))
print('This is the shape of the array', a.shape)
print('This the data type of the array ',a.dtype)

The datastruture is now  <class 'numpy.ndarray'>
This is the shape of the array (4,)
This the data type of the array  int64


In [5]:
# To the get the dimension of an array
# use the ndim function

print('This is the dimension of the array', a.ndim)

This is the dimension of the array 1


In [9]:
# creating another array
b = np.array([[1,2,3],[4,5,6]])
print('This is my array \n',b)

print('\n')
# checking the dimension array
print('this is the dimension of the array ',b.ndim)

print('This is shape of the array',b.shape)

This is my array 
 [[1 2 3]
 [4 5 6]]


this is the dimension of the array  2
This is shape of the array (2, 3)


 There are also some inbuilt functions  that can be used  to initialize numpy which include empty(), zeroes, ones(), random.random()


In [10]:
# a 2 by 3 array with random values
np.random.random((2,3))


array([[0.84501027, 0.11659807, 0.71487495],
       [0.7475634 , 0.62198521, 0.99350897]])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Intra-operability of arrays and scalar

In [18]:
c = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])

e = c+d
h = c*d
g = 5 / d
p = c ** 2
print('adding the array \n',e)
print('multiply the array \n', h)
print('5 divided by array d \n', g)
print('power of 2 for array c \n', p)


adding the array 
 [[13. 13. 13.]
 [10. 10. 10.]]
multiply the array 
 [[36. 40. 42.]
 [ 9. 16. 21.]]
5 divided by array d 
 [[1.25       1.         0.83333333]
 [0.55555556 0.625      0.71428571]]
power of 2 for array c 
 [[81. 64. 49.]
 [ 1.  4.  9.]]


In [23]:
a[3]

8